### ISSUE TITLE
Trying to create a madFile

### ISSUE THREAD

**Issue by EliosSs** [jaqx0r/pymad#11]
Hey, My name is Eliomar.
I am a bit new on this, and also I am new with python.
I am trying to test the software with the "test.py" file, in the description you say that a mad.MadFile, how I do this? isn't a predefined mad.MadFile with the project?
I was finding on internet how to do that but I didn't found anything. Can you give me an example?
I tried with some links of youtube (streaming audio with mpeg format no?) but nothing happened, It just give me this messages (Attached picture).

I also tried with madradio.py but it gives me an error with "import ao", I tried to install it with pip but it gives me an error.

Could you help me with this? sorry if some of these questions are stupid, I just have few days programming with python.

Regards and thanks.
![screenshot from 2018-08-23 18-49-08](https://user-images.githubusercontent.com/35732290/44555894-47700980-a705-11e8-9f2f-1457910eb55b.png)

**Comment by jaqx0r** [comment]
Well I'm very sorry for not replying until now.

I don't know if you can stream an MP3 channel from a youtube video.
