### ISSUE TITLE
Website should be updated

### ISSUE THREAD

**Issue by Holzhaus** [jaqx0r/pymad#4]
The Website at http://spacepants.org/src/pymad/ is quite outdated.

> The latest version of the source code is kept in arch:
> ```
> baz register-archive http://arch.spacepants.org/jaq@spacepants.org--2004
> baz get jaq@spacepants.org--2004/pymad--main--0
> ```

People who are interested in helping out should be pointed to this Git repository instead of the baz repo, since development seems to happen here.

> The latest stable release of pymad can be downloaded from [here](http://spacepants.org/src/pymad/download/).

That should be a link to https://github.com/jaqx0r/pymad/releases instead.

**Comment by jaqx0r** [comment]
Yup. I've lost the source to the site :)

I should just do it live.

**Comment by jaqx0r** [comment]
Done.
