### ISSUE TITLE
Output Sample Width?

### ISSUE THREAD

**Issue by julianofoleiss** [jaqx0r/pymad#6]
Hello!

I wish to use pymad to decode MP3 files into a PCM stream. The main problem I'm having is figuring out the output sample width. Is there any way to query this? Without this information it is impossible to make sense of the buffer output from MadFile.read since there's no way to know how many bytes make up a single sample.

Thanks!

**Comment by petli** [comment]
It is implied by PCM data: that use 2 bytes signed integers for the samples, and a stereo frame is thus 4 bytes.  The buffer data contains a sequence of frames, and in each frame first a sample for the left channel, then a sample for the right channel.

I'm not sure if PCM specifies an endianness to the data (e.g. PCM on CDs use big-endian), but pymad will return data in host byte order. On x86 that's little endian.

**Comment by saleh1100** [comment]
Q📻[📺[_****_](https://stadia.com/link/?link=https://stadia.google.com/player/a4c5eb3f4e614b7fadbba64cba68f849rcp1?fallback_sku%3D480a6d783c834b9faa5c995f69b49431%26link_id%3D8517360941251284199&apn=com.google.stadia.android&amv=15113&isi=1471900213&ibi=com.google.stadia&st=PlayerUnknown%27s+Battlegrounds+-+Payback+Edition&si=https://ssl.gstatic.com/stadia/gamers/assets/stadia_logo_and_text_v1.jpg&cid=1601959530215184629&_osl=https://stadia.com/link/HR7G3nYXi9uRJQMX9?_iipp%3D1&_iipp=1&_icp=1)](https://stadia.com/link/?link=https://stadia.google.com/player/a4c5eb3f4e614b7fadbba64cba68f849rcp1?fallback_sku%3D480a6d783c834b9faa5c995f69b49431%26link_id%3D8517360941251284199&apn=com.google.stadia.android&amv=15113&isi=1471900213&ibi=com.google.stadia&st=PlayerUnknown%27s+Battlegrounds+-+Payback+Edition&si=https://ssl.gstatic.com/stadia/gamers/assets/stadia_logo_and_text_v1.jpg&cid=1601959530215184629&_osl=https://stadia.com/link/HR7G3nYXi9uRJQMX9?_iipp%3D1&_iipp=1&_icp=1)
