### ISSUE TITLE
Not able to install it using pip

### ISSUE THREAD

**Issue by inkrement** [jaqx0r/pymad#7]
Although, there is a pypi entry, I was not able to install the package using pip (e.g., `pip install pymad`). Would be great if this would be possible.. Cloning and running the build/setup tools worked, but pip would be easier :)

**Comment by jaqx0r** [comment]
I don't know how to do this. Could you send a PR?

**Comment by inkrement** [comment]
I have to admit, that I never did this before, but [some user](https://github.com/pypa/packaging-problems/issues/60) explained the required steps in this Issue. I think you already publised your package to PyPI, but in my case pip returned `No distributions at all found for ...`. Therefore I think you have to "build and upload" the project.

**Comment by tgarc** [comment]
pymad (0.8) is the right package but if you check the PyPI page there are no download links hence why it's listed in pip search results but not installable.

I think using [twine](https://pypi.python.org/pypi/twine) is standard practice for deploying python packages. It's essential just this:

```
$ twine register dist/project_name-x.y.z.tar.gz
$ twine upload dist/*
```

But look at the twine pypi page for more info. You might also want to first test deploying to the testpypi server.

**Comment by jaqx0r** [comment]
Thanks!

**Comment by jaqx0r** [comment]
ETA for a fix for this is in two weeks when I get back to my regular workstation.

**Comment by jaqx0r** [comment]
https://pypi.org/project/pymad/0.9/#files

This is now done!  Thanks everyone for the advice.

**Comment by wiseman** [comment]
BTW, if you try to `pip install pymad` in Mac OS and get this error:
```
    src/madmodule.c:11:10: fatal error: 'mad.h' file not found
    #include <mad.h>
             ^~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
```

Then you need to install the mad package first: `brew install mad`.

**Comment by jaqx0r** [comment]
If someone who understands how all this works can send me a PR or tell me
what buttons to click in pypi, I'd appreciate it.
